### ISSUE TITLE
UnsatisfiedLinkError on Samsung Galaxy S7

### ISSUE THREAD

**Issue by mattfiocca** [dbankier/HasMenu#1]
Here is contents of a crash log from one of our Samsung Galaxy S7 users:

```
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.empowerpc.empower-1/lib/arm/libyy.hasmenu.so: has text relocations
    at java.lang.Runtime.loadLibrary(Runtime.java:372)
    at java.lang.System.loadLibrary(System.java:1076)
    at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
    at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
    at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
    at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
```

Device Specs:

```
Android 6.0
Manufacturer Samsung 
Android version Android 6.0 
RAM (MB) 4096 
Screen size 1440 × 2560 
Screen density (dpi) 640 
OpenGL ES version 3.1 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8996
```

I can confirm that the .so files are present in my project, so they _should_ be included when packaging the app. Is there anything that I might be missing here? Our app does not crash on earlier droid device models

**Comment by mattfiocca** [comment]
I was able to get this working just fine by recompiling this module against the latest ndk.
